### PR TITLE
Updates for Docker 1.9 Support

### PR DESCRIPTION
**Pull request by davidamin**

### CODE REVIEW

**Comment by davidamin** [comment]
Were those issues related to setting /etc/hosts up? Adding the --hostname argument fixed those for me in 1.9, and everything else seemed to work correctly (though I remember memory quickly becoming an issue last semester)

I'll update the examples to use compose and touch base with Ian on ES compatibility.

**Comment by davidamin** [comment]
Just checked Slack, it seems like the problems got patched in 0.8.2 (and the image is on 0.8.2.1 I believe) so we might be okay? I couldn't find good steps to reproduce, but I can try to test it out if it's a worry. Also, seems like they've added an environment variable for auto creating topics, which I believe might solve the issues where we had to fail on topic creation once before subsequent requests could go through. I'll test it asap to be sure though

**Comment by thomaspinckney3** [comment]
Sounds good. 

As best I can recall Kafka would refuse to start or maybe accept writes the second time you tried to run it.

**Comment by zeizyy** [comment]
I looked into the kafka-python documentation and I think the reason kafka fails on sending the first message is that SimpleProducer sends message in synchronous mode. Since topic creation takes time, it fails on sending the first message. I also found that SimpleProducer is deprecated in the most recent version of Kafka (1.0.2) (http://kafka-python.readthedocs.org/en/master/simple.html#simpleproducer-deprecated). I try upgraded kafka-python in container and everything works out fine. I will submit a pull request for this.

**Pull request merged**
